github: millsp
custom: https://www.buymeacoffee.com/millsp
patreon: millsp
issuehunt: https://issuehunt.io/r/pirix-gh/ts-toolbelt
tidelift: https://tidelift.com/subscription/pkg/npm-ts-toolbelt?utm_source=npm-ts-toolbelt&utm_medium=referral&utm_campaign=readme
