# https://docs.travis-ci.com/user/job-lifecycle

language: node_js

node_js:
- '10.0'

install:
- npm run setup:dev

stages:
  - test
  - deploy:master
  - deploy:branch

jobs:
  include:
    - stage: test
      if: tag IS blank # filter double build with tags
      script:
        - npm run ci:test 
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        tag: test
        on:
          all_branches: true
      before_deploy: # https://github.com/travis-ci/travis-ci/issues/1574#issuecomment-451787844
        - if ! npm run ci:test:bd; then travis_terminate 1; fi
      after_deploy: # the above link explains how to make the build fail if something went wrong
        - if ! npm run ci:test:ad; then travis_terminate 1; fi

    - stage: deploy:master
      if: tag IS blank AND branch = master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: latest
        skip_cleanup: true
        on:
          all_branches: true
      before_deploy:
        - if ! npm run ci:branch:bd; then travis_terminate 1; fi
      after_deploy:
        - if ! npm run ci:branch:ad; then travis_terminate 1; fi
  
    - stage: deploy:branch
      if: tag IS blank AND branch != master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: $TRAVIS_BRANCH
        skip_cleanup: true
        on:
          all_branches: true
      before_deploy:
        - if ! npm run ci:branch:bd; then travis_terminate 1; fi
      after_deploy:
        - if ! npm run ci:branch:ad; then travis_terminate 1; fi
