# https://docs.travis-ci.com/user/job-lifecycle

language: node_js

node_js:
- '10.0'

install:
- npm run setup:dev

stages:
  - test
  - name: deploy:master
    if: tag IS NOT blank
  - name: deploy:branch
    if: tag IS blank

jobs:
  include:
    - stage: test
      script:
        - npm run ci:test
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        tag: test
        on:
          all_branches: true
      before_deploy:
        - npm run ci:test:bd
      after_deploy:
        - npm run ci:test:ad

    - stage: deploy:master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: latest
        skip_cleanup: true
        on:
          all_branches: true
      before_deploy:
        - npm run ci:branch:bd
      after_deploy:
        - npm run ci:branch:ad
  
    - stage: deploy:branch
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: $TRAVIS_BRANCH
        skip_cleanup: true
        on:
          all_branches: true
      before_deploy:
        - npm run ci:branch:bd
      after_deploy:
        - npm run ci:branch:ad
