# https://docs.travis-ci.com/user/job-lifecycle

language: node_js

node_js:
- '8.0'

install:
- npm run setup:dev

stages:
  - test
  - deploy:master
  - deploy:branch

jobs:
  include:
    - stage: test
      script:
        - npm run ci:test
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        tag: test
        on:
          all_branches: true
      before_deploy:
        - npm run ci:bd:test
      after_deploy:
        - npm run ci:ad:test

    - stage: deploy:master
      if: branch = master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          all_branches: true

    - stage: deploy:branch
      if: branch != master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: $TRAVIS_BRANCH
        skip_cleanup: true
        on:
          all_branches: true
