# https://docs.travis-ci.com/user/job-lifecycle

language: node_js

node_js:
- '8.0'

install:
- npm run setup:dev

stages:
  - test
  - deploy:master
  - deploy:branch

jobs:
  include:
    - stage: test
      script:
        - npm run release:ci
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        tag: dt
        on:
          all_branches: true
      after_deploy:
        - npm run release:ci:dt

    - stage: deploy:master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          all_branches: true

    - stage: deploy:branch
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: $TRAVIS_BRANCH
        skip_cleanup: true
        on:
          all_branches: true
