language: node_js
node_js:
- '8.0'
before_install:
- npm run setup:dev
script:
- npm run release:ci
jobs:
  include:
    - stage: master
      if: branch = master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          all_branches: true
    - stage: branch
      if: branch != master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        tag: $TRAVIS_BRANCH
        skip_cleanup: true
        on:
          all_branches: true
